"""Unified diff generator for config file patches.

Takes a verified fix (from the hypothesis / sandbox verifier) and a target
file, and produces a unified diff. Understands the structure of common config
files: Dockerfile, requirements.txt, .env, docker-compose.yml, pyproject.toml.

The diff is generated by:
1. Reading the original file content
2. Applying the fix_code transformation to produce the new content
3. Using Python's difflib to produce a unified diff
"""

from __future__ import annotations

import difflib
import re
from pathlib import Path
from typing import Any

from .models import PatchRecord, PatchStatus, TargetFileType


def detect_target_type(filepath: str) -> TargetFileType:
    """Detect the type of config file from its name."""
    name = Path(filepath).name.lower()
    if name == "dockerfile" or name.startswith("dockerfile."):
        return TargetFileType.DOCKERFILE
    if name in ("requirements.txt", "requirements-dev.txt", "requirements-test.txt"):
        return TargetFileType.REQUIREMENTS
    if name == ".env" or name.startswith(".env."):
        return TargetFileType.ENV_FILE
    if name in ("docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"):
        return TargetFileType.DOCKER_COMPOSE
    if name == "pyproject.toml":
        return TargetFileType.PYPROJECT
    return TargetFileType.GENERIC


def _apply_env_var_fix(content: str, fix_code: str) -> str:
    """Apply an env var fix to a .env file or Dockerfile.

    Handles patterns like:
    - export VAR='value'
    - ENV VAR=value
    - VAR=value
    """
    assignments = re.findall(
        r"(?:export\s+|ENV\s+)?(\w+)\s*=\s*['\"]?([^'\"\n]*)['\"]?",
        fix_code,
    )

    lines = content.splitlines(keepends=True)
    if lines and not lines[-1].endswith("\n"):
        lines[-1] += "\n"

    for var_name, var_value in assignments:
        found = False
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            if re.match(rf"^(?:export\s+|ENV\s+)?{re.escape(var_name)}\s*=", stripped):
                if stripped.startswith("ENV "):
                    lines[i] = f"ENV {var_name}={var_value}\n"
                elif stripped.startswith("export "):
                    lines[i] = f"export {var_name}='{var_value}'\n"
                else:
                    lines[i] = f"{var_name}={var_value}\n"
                found = True
                break
        if not found:
            lines.append(f"{var_name}={var_value}\n")

    return "".join(lines)


def _apply_package_fix(content: str, fix_code: str) -> str:
    """Apply a package version fix to requirements.txt.

    Handles patterns like:
    - pip install pkg==version
    - pkg==version
    """
    pkg_specs = re.findall(
        r"(?:pip\s+install\s+)?(\w[\w.-]*)(?:[=<>!~]+)([\w.*]+)",
        fix_code,
    )

    lines = content.splitlines(keepends=True)
    if lines and not lines[-1].endswith("\n"):
        lines[-1] += "\n"

    for pkg_name, pkg_version in pkg_specs:
        found = False
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith("#") or not stripped:
                continue
            existing = re.match(
                rf"^{re.escape(pkg_name)}(?:\[.*\])?\s*([=<>!~]+.*)$",
                stripped,
                re.IGNORECASE,
            )
            if existing:
                bracket = ""
                bracket_match = re.match(
                    rf"^{re.escape(pkg_name)}(\[.*\])",
                    stripped,
                    re.IGNORECASE,
                )
                if bracket_match:
                    bracket = bracket_match.group(1)
                lines[i] = f"{pkg_name}{bracket}=={pkg_version}\n"
                found = True
                break
        if not found:
            lines.append(f"{pkg_name}=={pkg_version}\n")

    return "".join(lines)


def _apply_dockerfile_fix(content: str, fix_code: str) -> str:
    """Apply a fix to a Dockerfile.

    Handles:
    - ENV VAR=value — update existing ENV line or add before CMD/ENTRYPOINT
    - RUN commands — add before first CMD/ENTRYPOINT
    - Package installs — modify existing apt-get install lines
    """
    lines = content.splitlines(keepends=True)
    if lines and not lines[-1].endswith("\n"):
        lines[-1] += "\n"

    if re.match(r"^\s*ENV\s+", fix_code):
        env_match = re.match(r"^\s*ENV\s+(\w+)\s*=\s*(.*)", fix_code)
        if env_match:
            var_name = env_match.group(1)
            var_value = env_match.group(2).strip().strip("'\"")
            found = False
            for i, line in enumerate(lines):
                if re.match(rf"^\s*ENV\s+{re.escape(var_name)}\s*=", line.strip()):
                    lines[i] = f"ENV {var_name}={var_value}\n"
                    found = True
                    break
            if not found:
                insert_idx = len(lines)
                for i, line in enumerate(lines):
                    if re.match(r"^\s*(CMD|ENTRYPOINT)\s", line):
                        insert_idx = i
                        break
                lines.insert(insert_idx, f"ENV {var_name}={var_value}\n")
            return "".join(lines)

    insert_idx = len(lines)
    for i, line in enumerate(lines):
        if re.match(r"^\s*(CMD|ENTRYPOINT)\s", line):
            insert_idx = i
            break

    fix_line = fix_code.strip()
    if not fix_line.startswith("RUN "):
        fix_line = f"RUN {fix_line}"

    lines.insert(insert_idx, fix_line + "\n")
    return "".join(lines)


def apply_fix_to_content(
    content: str,
    fix_code: str,
    target_type: TargetFileType,
) -> str:
    """Apply a fix_code to file content based on the target file type.

    Args:
        content: Original file content
        fix_code: The fix command/code from the hypothesis
        target_type: Type of the target file

    Returns:
        Modified file content
    """
    if target_type == TargetFileType.ENV_FILE:
        return _apply_env_var_fix(content, fix_code)
    if target_type == TargetFileType.REQUIREMENTS:
        return _apply_package_fix(content, fix_code)
    if target_type == TargetFileType.DOCKERFILE:
        return _apply_dockerfile_fix(content, fix_code)
    if target_type == TargetFileType.DOCKER_COMPOSE:
        return _apply_env_var_fix(content, fix_code)
    return _apply_env_var_fix(content, fix_code)


def generate_diff(
    original: str,
    modified: str,
    filepath: str,
) -> str:
    """Generate a unified diff between original and modified content.

    Args:
        original: Original file content
        modified: Modified file content
        filepath: File path for the diff header

    Returns:
        Unified diff string
    """
    original_lines = original.splitlines(keepends=True)
    modified_lines = modified.splitlines(keepends=True)

    diff_lines = difflib.unified_diff(
        original_lines,
        modified_lines,
        fromfile=f"a/{filepath}",
        tofile=f"b/{filepath}",
        lineterm="",
    )
    return "\n".join(line.rstrip("\n") for line in diff_lines)


def create_patch_record(
    fix_code: str,
    target_file: str,
    content: str,
    trace_id: str = "",
    case_id: str = "",
    confidence: float = 0.0,
    description: str = "",
) -> PatchRecord:
    """Create a PatchRecord from a fix and its target file.

    Reads the file content, applies the fix, generates the diff, and
    packages everything into a PatchRecord.

    Args:
        fix_code: The fix command/code from the hypothesis
        target_file: Path to the target file
        content: Current content of the target file
        trace_id: Investigation trace ID
        case_id: Case ID for tracking
        confidence: Confidence score of the fix
        description: Human-readable description of the fix

    Returns:
        PatchRecord with diff and original/patched content
    """
    target_type = detect_target_type(target_file)
    patched = apply_fix_to_content(content, fix_code, target_type)
    diff = generate_diff(content, patched, target_file)

    return PatchRecord(
        case_id=case_id,
        trace_id=trace_id,
        target_file=target_file,
        target_type=target_type,
        diff_text=diff,
        original_content=content,
        patched_content=patched,
        description=description,
        fix_code=fix_code,
        confidence=confidence,
        status=PatchStatus.PROPOSED,
    )


def infer_target_file(
    fix_code: str,
    delta_type: str = "",
    repo_path: str | Path = ".",
) -> str | None:
    """Try to infer which file the fix targets from the fix_code.

    Heuristics:
    - export/ENV VAR= → .env or Dockerfile
    - pip install → requirements.txt
    - apt-get install → Dockerfile
    """
    repo = Path(repo_path)

    if re.search(r"\bpip\s+install\b", fix_code, re.IGNORECASE):
        for candidate in ["requirements.txt", "requirements-dev.txt"]:
            if (repo / candidate).exists():
                return candidate
        return "requirements.txt"

    if re.search(r"\bapt-get\s+install\b", fix_code, re.IGNORECASE):
        for candidate in ["Dockerfile", "dockerfile", "Dockerfile.dev"]:
            if (repo / candidate).exists():
                return candidate
        return "Dockerfile"

    if re.match(r"^\s*ENV\s+", fix_code):
        for candidate in ["Dockerfile", "dockerfile"]:
            if (repo / candidate).exists():
                return candidate
        return "Dockerfile"

    if re.match(r"^\s*export\s+", fix_code) or re.match(r"^\w+=", fix_code):
        for candidate in [".env", ".env.local", ".env.production"]:
            if (repo / candidate).exists():
                return candidate
        return ".env"

    return None
